name: theromanticbloke
favicon: null
layout_spectrum: 0.6648746
typography_spectrum: 0.5231
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bae6fd'
    - '#3f6389'
    - '#679cd7'
    - '#091500'
    - '#756000'
  brandStrength: 0.5
  lightness: 0.3942652
  saturation: 0.3315412
  rhythmicContrast: 0.265233
purpose: []
